
trigger:
- master

pool:
  name: AA-CICD-VM

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\dummyscript.ps1'
    arguments:

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--output $(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DotNetCore'
    publishLocation: 'Container'
